language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vladilenius/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true vladilenius/docker-react npm run test

